# Generated by Django 3.1 on 2020-11-02 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='finance.account'),
        ),
        migrations.AlterField(
            model_name='income',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incomes', to='finance.account'),
        ),
        migrations.AlterField(
            model_name='recurringincome',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='recurringincome',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='recurringpayment',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='recurringpayment',
            name='start_date',
            field=models.DateField(),
        ),
    ]
