# Generated by Django 3.1 on 2020-11-07 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_auto_20201102_0515'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='recurring_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='finance.recurringpayment'),
        ),
        migrations.AddField(
            model_name='income',
            name='recurring_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incomes', to='finance.recurringincome'),
        ),
        migrations.AlterField(
            model_name='recurringpayment',
            name='end_date',
            field=models.DateField(blank=True),
        ),
    ]
