# Generated by Django 3.1 on 2020-11-07 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_auto_20201107_0614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurringpayment',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
