# Generated by Django 3.1 on 2020-11-07 21:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_auto_20201107_0727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='added_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
