# Generated by Django 3.1 on 2020-10-18 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_auto_20201018_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='recurringincome',
            name='description',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='recurringincome',
            name='schedule_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='recurringpayment',
            name='description',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='recurringpayment',
            name='schedule_type',
            field=models.CharField(max_length=50),
        ),
    ]
