# Generated by Django 3.1 on 2020-11-09 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_auto_20201108_0219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurringincome',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recurringpayment',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rec_expenses', to='finance.account'),
        ),
        migrations.AlterField(
            model_name='recurringpayment',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
