# Generated by Django 3.1 on 2020-11-09 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_auto_20201109_0219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurringpayment',
            name='start_date',
            field=models.DateField(),
        ),
    ]
