# Generated by Django 3.1 on 2020-11-09 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_auto_20201109_0229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurringpayment',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
