# Generated by Django 3.1 on 2020-11-20 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_auto_20201116_0259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurringincome',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rec_incomes', to='finance.account'),
        ),
        migrations.AlterField(
            model_name='recurringincome',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recurringincome',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
