# Generated by Django 3.1 on 2020-11-21 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0012_auto_20201120_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='recurring_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='finance.recurringpayment'),
        ),
        migrations.AlterField(
            model_name='income',
            name='recurring_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='finance.recurringincome'),
        ),
    ]
