# Generated by Django 3.1 on 2020-12-01 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0013_auto_20201121_0440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='category',
        ),
        migrations.RemoveField(
            model_name='income',
            name='category',
        ),
        migrations.RemoveField(
            model_name='recurringincome',
            name='category',
        ),
        migrations.RemoveField(
            model_name='recurringpayment',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
